### ISSUE TITLE
Any Planned CanvasAPI Releases?

### ISSUE THREAD

**Issue by joshruesch** [instructure/CanvasAPI#207]
There hasn't been any releases to the Maven repo since late May when @nbutton23 published new artifacts. Is there any plans for a new .aar release? or should I just continue building from source?

**Comment by matthewrice345** [comment]
We will update when we are ready.

**Comment by joshruesch** [comment]
I was just curious as to when to expect the new features I've seen filtering in. Is there any sort of time-frame I can expect or just it'll happen when it happens?
