### ISSUE TITLE
What is the CanvasContext in AnnouncementAPI call and what values it need ?

### ISSUE THREAD

**Issue by 34tm4n** [instructure/CanvasAPI#334]
I am trying to get announcements from AnnouncementApi.AnnouncementAPI.getFirstPageAnnouncements call but it needs CanvasContext.
From where i'll get its fields values ?
new CanvasContext() {
            @Override
            public String getName() {
                return null;
            }
            @Override
            public Type getType() {
                return null;
            }
            @Override
            public long getId() {
                return 0;
            }
            @Override
            public void writeToParcel(Parcel parcel, int i) {
            }

**Comment by matthewrice345** [comment]
CanvasContext is an object used to declare a few types of concepts in one format. The types are GROUP, COURSE, USER, SECTION (see CanvasContext in the api for more info. 
A context_id is a common way in the api to say the id being passed is a course or group. Example course_123456 where 123456 is the id of the course. When passing a CanvasContext we will use the id to build the context_id to pass to the api. 

Typically you'll get those fields when you pull down a users groups and courses. Again looking at the api you'll see that a course and group both extend a CanvasContext.
