### ISSUE TITLE
Which API is for getting the replies of an announcements ?

### ISSUE THREAD

**Issue by 34tm4n** [instructure/CanvasAPI#335]
I am getting Announcements of a users using AnnouncementsApi.getFirstPageAnnouncements(). Now I want to show the replies of that announcements and want to reply to that announcement. But i am not able to find any api related to Showing replies or Do Replies on
https://canvas.instructure.com/doc/api/
Which api's should i use from them.

Thanks In Advance

**Comment by hhoang** [comment]
Hey @34tm4n  Thanks for your interest in the project. 
Announcements in canvas are also Discussions Topics. [You can find more information on how to get replies here](https://canvas.instructure.com/doc/api/discussion_topics.html)

In short, you can get access to a full discussion topic using the `/discussion_topics/{discussion_id}/view` endpoint. The `DiscussionAPI` class also has a `getFullDiscussionTopic()` which will return a DiscussionTopic.
I'm closing this issue for now but if you have further questions, feel free to ask, or open a new issue if you encounter a bug.
