### ISSUE TITLE
Requests Caching

### ISSUE THREAD

**Issue by ShamsUlAzeem** [instructure/CanvasAPI#336]
I am getting null object when I call UserAPI.getSelf. It always execute the cached function and returns null object. What am I doing wrong here?

**Comment by hhoang** [comment]
Hey @ShamsUlAzeem could you provide an example of how you're calling UserAPI.getSelf()?
We have a UserCallback helper which might be of some use to you.
Something like this should work.
```
 UserAPI.getSelf(new UserCallback(APIHelpers.statusDelegateWithContext(OAuthWebLogin.this)) {
            @Override
            public void cachedUser(User user) {
                // will be null on the initial call. UserCallback will auto cache the user returned by the API 
                // using the APIHelpers.setCacheUser() method.
            }

            @Override
            public void user(User user, Response response){
            }
        });
```
